services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_MODE=${ENV_MODE}
      ssh:
        - default
    restart: always
    volumes:
      - logs:/app/logs
      - ./app:/app/app
    ports:
      - "8000:8000"
    environment:
      - ENV_MODE=${ENV_MODE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/app"]
    env_file:
      - .env

volumes:
  logs:
