name: Backup deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  Build:
    name: Setup Chatbot Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.branch }}

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Vultr Container Registry
        run: |
          docker login -u ${{ secrets.VULTR_REGISTRY_USERNAME }} -p ${{ secrets.VULTR_REGISTRY_PASSWORD }} ${{ secrets.VULTR_REGISTRY_URL }}

      - name: Build and push Docker image
        run: |
          export DOCKER_BUILDKIT=1
          REGISTRY_PATH="syd.vultrcr.com/qlink01/aura_serve"
          docker build -t $REGISTRY_PATH:latest .
          docker push $REGISTRY_PATH:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USERNAME }} 
          password: ${{ secrets.SERVER_PASSWORD }} 
          script: |
            # Login to Vultr Container Registry
            docker login -u ${{ secrets.VULTR_REGISTRY_USERNAME }} -p ${{ secrets.VULTR_REGISTRY_PASSWORD }} ${{ secrets.VULTR_REGISTRY_URL }}

            # Pull the latest image
            docker pull syd.vultrcr.com/qlink01/aura_serve:latest

            # Stop and remove existing container if it exists
            docker stop qlink || true
            docker rm qlink || true

            # Run new container
            docker run -d --name qlink -p 8000:8000 \
            -e PYTHONUNBUFFERED=1 \
            -e PYTHONDONTWRITEBYTECODE=1 \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e APP_PASSWORD=${{ secrets.APP_PASSWORD }} \
            -e PINECONE_API=${{ secrets.PINECONE_API }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            -e LOGIN_USERNAME=${{ secrets.LOGIN_USERNAME }} \
            -e LOGIN_PASS=${{ secrets.LOGIN_PASS }} \
            -e RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }} \
            -e RAZORPAY_APP_ID=${{ secrets.RAZORPAY_APP_ID }} \
            -e RAZORPAY_APP_SECRETE=${{ secrets.RAZORPAY_APP_SECRETE }} \
            -e TEST_RAZORPAY_APP_ID=${{ secrets.TEST_RAZORPAY_APP_ID }} \
            -e TEST_RAZORPAY_APP_SECRETE=${{ secrets.TEST_RAZORPAY_APP_SECRETE }} \
            -e ADMIN_API_KEY=${{ secrets.ADMIN_API_KEY }} \
            -e SARVAM_API=${{ secrets.SARVAM_API }} \
            -e BREVO_API_KEY=${{ secrets.BREVO_API_KEY }} \
            -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            -e R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }} \
            -e R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }} \
            -e R2_ENDPOINT=${{ secrets.R2_ENDPOINT }} \
            -e R2_BUCKET=${{ secrets.R2_BUCKET }} \
            -e ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }} \
            -e R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }} \
            syd.vultrcr.com/qlink01/aura_serve:latest

      - name: Cleanup Old Images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}    
          username: ${{ secrets.SERVER_USERNAME }}   
          password: ${{ secrets.SERVER_PASSWORD }}   
          script: |
            # Remove dangling images to free up space
            docker image prune -f

